---
title: "Take Me Out to Which Ballgame?"
author: "Jay-Ho Chung, Brigitte Goeler-Slough, Nathan Ives"
date: "4/23/2018"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    theme: spacelab
---

```{r (Packages), warning = FALSE, message = FALSE}
library(mdsr)
library(RMySQL)
library(tidyverse)
```

```{r (Connecting to the Database)}
db <- dbConnect_scidb(dbname = "lahman")
```

```{r (Pitchers), warning = FALSE}
pitchers <- db %>% 
  dbGetQuery(
    "SELECT hof.playerID, hof.yearID, nameFirst, nameLast, 
    sum(G) as G, sum(pi.GS) as GS, sum(IPouts/3) as IP, 
    sum(CG) as CG, sum(SHO) as SHO, sum(SV) as SV, sum(W) as W,
    sum(L) as L, sum(H) as H, sum(BB) as BB, sum(ER) as ER,
    sum(SO) as SO, ((sum(ER) / (sum(IPouts)/3)) * 9) as ERA, 
    ((sum(H) + sum(BB)) / (sum(IPouts) / 3)) as WHIP
    FROM HallOfFame hof
    JOIN Master ma ON ma.playerID = hof.playerID
    JOIN Pitching pi ON pi.playerID = hof.playerID
    WHERE hof.inducted = 'Y'
    GROUP BY hof.playerID
HAVING G > 100;"
  )
pitchers
```

```{r (Hitters), warning = FALSE}
hitters <- db %>% 
  dbGetQuery("SELECT hof.playerID, hof.yearID, nameFirst,
              nameLast, sum(AB) as AB, sum(R) as R, sum(H) as H,
              sum(2B) as 2B, sum(3B) as 3B, sum(HR) as HR,
              sum(RBI) as RBI, sum(SB) as SB, 
              (sum(H) / sum(AB)) as AVG
              FROM HallOfFame hof
              JOIN Master ma ON ma.playerID = hof.playerID
              JOIN Batting ba ON ba.playerID = hof.playerID
              WHERE hof.inducted = 'Y'
              GROUP BY hof.playerID
              HAVING AB > 2000;")
hitters
```

```{r (not inducted), warning = FALSE}
not_inducted <- db %>%
  dbGetQuery("SELECT playerID, yearid, ballots, needed, votes, inducted, 
sum(inducted = 'Y') as indct
FROM HallOfFame
GROUP BY playerID
HAVING indct = 0")
not_inducted
```

```{r (batteres not inducted), warning = FALSE}
batters_not_inducted <- db %>% 
  dbGetQuery("SELECT hof.playerID, nameLast, nameFirst,
              count(DISTINCT hof.yearID) as num_ballots,
              min(hof.yearid) AS first_year, ballots, needed,
              votes, inducted, max(votes / ballots) as PCT,
              sum(AB) / count(DISTINCT hof.yearID) as AB, 
              sum(R) / count(DISTINCT hof.yearID) as R, 
              sum(H) / count(DISTINCT hof.yearID) as H,
              sum(2B) / count(DISTINCT hof.yearID) as 2B, 
              sum(3B) / count(DISTINCT hof.yearID) as 3B, 
              sum(HR) / count(DISTINCT hof.yearID) as HR,
              sum(RBI) / count(DISTINCT hof.yearID) as RBI,
              sum(SB) / count(DISTINCT hof.yearID) as SB, 
              (sum(H) / sum(AB)) as AVG,
              sum(inducted = 'Y') as indct
FROM HallOfFame as hof
JOIN Batting ba ON ba.playerID = hof.playerID
JOIN Master ma ON ma.playerID = hof.playerID
WHERE hof.yearid > 1979
GROUP BY hof.playerID
HAVING indct = 0
  AND AB > 4000
  AND PCT > 0.2
ORDER BY PCT desc;")

batters_not_inducted
```

```{r warning = FALSE}
pitchers_not_inducted <- db %>%
  dbGetQuery("SELECT hof.playerID, hof.yearID, ma.nameFirst, ma.nameLast, count(DISTINCT hof.yearID) as num_ballots, hof.ballots , hof.needed , hof.votes , max(votes/ballots) as PCT , hof.inducted,
    sum(inducted = 'Y') as indct ,sum(G)/(count(DISTINCT hof.yearID)) as G, sum(GS)/(count(DISTINCT hof.yearID)) as GS, sum(IPouts/3)/(count(DISTINCT hof.yearID)) as IP, 
    sum(CG) / (count(DISTINCT hof.yearID)) as CG, sum(SHO) / (count(DISTINCT hof.yearID)) as SHO, sum(SV) / (count(DISTINCT hof.yearID)) as SV, sum(W) / (count(DISTINCT hof.yearID)) as W,
    sum(L) / (count(DISTINCT hof.yearID)) as L, sum(H) / (count(DISTINCT hof.yearID)) as H, sum(BB) / (count(DISTINCT hof.yearID)) as BB, sum(ER) / (count(DISTINCT hof.yearID)) as ER,
    sum(SO)/(count(DISTINCT hof.yearID)) as SO, ((sum(ER) / (sum(IPouts)/3)) * 9) as ERA, 
    ((sum(H) + sum(BB)) / (sum(IPouts) / 3)) as WHIP 
FROM lahman.HallOfFame AS hof
JOIN lahman.Master AS ma on ma.playerID = hof.playerID
JOIN lahman.Pitching AS pi on pi.playerID = hof.playerID
GROUP BY ma.playerID
HAVING indct = 0
  AND PCT > 0.2
  AND G > 100
ORDER BY PCT desc;")

pitchers_not_inducted
# Use save() to save it as a .rda and then load() it later w/ eval = FALSE
```

```{r message = FALSE, warning = FALSE}
all_hitters <- hitters %>% 
  full_join(batters_not_inducted)

all_pitchers <- pitchers %>% 
  full_join(pitchers_not_inducted)
```

```{r}
ggplot(all_hitters, aes(x = AVG, y = HR)) +
  geom_point() +
  scale_y_continuous(limits = c(0, 800))
```

```{r}
ggplot(all_pitchers, aes(x = ERA, y = W)) +
  geom_point()
```

```{r fig.show = "hold", fig.width = 3.5}
ggplot(pitchers, aes(x = ERA, y = W)) + 
  geom_point() +
  ggtitle("Pitchers Inducted") +
  xlim(1.5,4) +
  ylim(0,520)

ggplot(pitchers_not_inducted, aes(x = ERA, y = W)) + 
  geom_point() +
  ggtitle("Pitchers not Inducted") +
  xlim(1.5,4) +
  ylim(0,520)
```

```{r fig.show = "hold", fig.width = 3.5}
ggplot(hitters, aes(x = AVG, y = HR)) +
  geom_point() +
  ggtitle("Hitters Inducted") +
  xlim(.15, .4) +
  ylim(0,850)

ggplot(batters_not_inducted, aes(x = AVG, y = HR)) +
  geom_point() +
  ggtitle("Hitters not Inducted") +
  xlim(0, .4) +
  ylim(.15,850)
```

```{r warning = FALSE}
both_hitters <- db %>% 
  dbGetQuery("SELECT hof.playerID, nameLast, nameFirst,
              count(DISTINCT hof.yearID) as num_ballots,
              min(hof.yearid) AS first_year, ballots, needed,
              votes, inducted, max(votes / ballots) as PCT,
              sum(AB) / count(DISTINCT hof.yearID) as AB, 
              sum(R) / count(DISTINCT hof.yearID) as R, 
              sum(H) / count(DISTINCT hof.yearID) as H,
              sum(2B) / count(DISTINCT hof.yearID) as 2B, 
              sum(3B) / count(DISTINCT hof.yearID) as 3B, 
              sum(HR) / count(DISTINCT hof.yearID) as HR,
              sum(RBI) / count(DISTINCT hof.yearID) as RBI,
              sum(SB) / count(DISTINCT hof.yearID) as SB, 
              (sum(H) / sum(AB)) as AVG
FROM HallOfFame as hof
JOIN Batting ba ON ba.playerID = hof.playerID
JOIN Master ma ON ma.playerID = hof.playerID
WHERE hof.yearid > 1979
GROUP BY hof.playerID
HAVING AB > 4000
  AND PCT > 0.2
ORDER BY PCT desc;")

ggplot(both_hitters, aes(x = AVG, y = HR, colour = inducted)) +
  geom_point() +
  ggtitle("All Hitters") +
  xlim(0, .4) +
  ylim(.15,850)
```

```{r warning = FALSE}
both_pitchers <- db %>% 
  dbGetQuery("SELECT hof.playerID, hof.yearID, ma.nameFirst, ma.nameLast, count(DISTINCT hof.yearID) as num_ballots, hof.ballots , hof.needed , hof.votes , max(votes/ballots) as PCT , hof.inducted,
    sum(G)/(count(DISTINCT hof.yearID)) as G, sum(GS)/(count(DISTINCT hof.yearID)) as GS, sum(IPouts/3)/(count(DISTINCT hof.yearID)) as IP, 
    sum(CG) / (count(DISTINCT hof.yearID)) as CG, sum(SHO) / (count(DISTINCT hof.yearID)) as SHO, sum(SV) / (count(DISTINCT hof.yearID)) as SV, sum(W) / (count(DISTINCT hof.yearID)) as W,
    sum(L) / (count(DISTINCT hof.yearID)) as L, sum(H) / (count(DISTINCT hof.yearID)) as H, sum(BB) / (count(DISTINCT hof.yearID)) as BB, sum(ER) / (count(DISTINCT hof.yearID)) as ER,
    sum(SO)/(count(DISTINCT hof.yearID)) as SO, ((sum(ER) / (sum(IPouts)/3)) * 9) as ERA, 
    ((sum(H) + sum(BB)) / (sum(IPouts) / 3)) as WHIP 
FROM lahman.HallOfFame AS hof
JOIN lahman.Master AS ma on ma.playerID = hof.playerID
JOIN lahman.Pitching AS pi on pi.playerID = hof.playerID
GROUP BY ma.playerID
HAVING PCT > 0.2
  AND G > 100
ORDER BY PCT desc;")

ggplot(both_pitchers, aes(x = ERA, y = W, color = inducted)) + 
  geom_point() +
  ggtitle("All Pitchers") +
  xlim(1.5,4) +
  ylim(0,520)
```


